### ISSUE TITLE
Figure out what patmos-ar does

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos-gold#1]
I will use this issue to track and communicate what the binary `patmos-ar`, which is produced by this repo, does.

[`ar` is "A utility for creating, modifying and extracting from archives."](https://www.gnu.org/software/binutils/). This utility is not architecture specific, so you would assume that the patmos project could use it as is. However, the patmos handbooks states that `patmos-ar` has some special support for  bitcode archives.

I am invested in what this "special" support is, and whether it is really needed. The goal is to be able to eliminate the use of `patmos-ar` in favor of either the normal `ar` or the `llvm-ar`, which also has support for bitcode.

Feel free to comment anything that might be relevant.

**Comment by michael-platzer** [comment]
I did a quick test to see whether using `patmos-ar` vs using the regular binutils `ar` produces a different archive/executable. It does, but it is only one symbol name in the symbol table that is different. The machine code is not affected.

To test this I created a static library that contains one object file, once using `patmos-ar` and once using the regular `ar`. Then I linked that library with a test program. The symbol name that changes is the following:

    # patmos-ar
    $ readelf -s sp-tests.elf | grep "tmp/sp-tests-"
         1: 00000000     0 FILE    LOCAL  DEFAULT  ABS /tmp/sp-tests-c736aa.bc
    
    # ar
    $ readelf -s sp-tests.elf | grep "tmp/sp-tests-"
         1: 00000000     0 FILE    LOCAL  DEFAULT  ABS /tmp/sp-tests-387e4b.bc

The name of that symbol seems to contain the directory in which the archive was created (which is `sp-tests`) and a hash value that is the only difference between `patmos-ar` and `ar`. Other than that symbol name the entire ELF executable is identical.

Interestingly it does not make a difference whether the object file used to produce the library is an ELF object file or a LLVM IR object file. `patmos-ar` as well as the regular `ar` will happily accept both formats. Apparently `ar` does not care about the contents of the file at all, it simply produces an archive containing the specified files.

**Comment by schoeberl** [comment]
We had in the past an issue when using the locally installed ar instead of patmos-ar. One developer changed to ar and it worked in his OS, but it broke on a different Os (maybe macOS, but I don't remember). So keeping "our" patmos-ar would be on the safe side.

**Comment by Emoun** [comment]
Throughout my work on updating to LLVM 12, I have used to normal `ar` without issue. This includes compiling and packaging newlib and compiler-rt. 
Therefore, I think it's safe to say `patmos-ar` is not needed.
